# Generated by Django 4.2.18 on 2025-03-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipment_added_by_equipment_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
