# Generated by Django 5.1.6 on 2025-03-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipment_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='current_user',
        ),
    ]
