# Generated by Django 4.2.18 on 2025-04-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_equipment_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sports_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
