# Generated by Django 4.2.18 on 2025-04-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_borrowrequest_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_equipment', to=settings.AUTH_USER_MODEL),
        ),
    ]
